name: Delete Older Releases
description: delete older releases of any repo
author: dev-drprasad

branding:
  color: red
  icon: delete

inputs:
  keep_latest:
    description: how many latest releases to keep
    required: true
  repo:
    description: repo name in the form of <owner>/<repoName>
    required: false
  delete_tags:
    description: whether to delete tags associated to older releases or not
    required: false
  delete_tag_regex:
    description: Regular expression for the tags you want to delete
    required: false
  prerelease_only:
    description: only delete pre-releases

runs:
  using: "node16"
  main: "index.js"
